[package]
name = "rofis"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
bytecodec = "0.4"
clap = "2"
fibers = "0.1"
fibers_http_server = "0.1"
futures = "0.1"
httpcodec = "0.2"
slog = "2"
sloggers = "0.2"
trackable = "0.2"